### ISSUE TITLE
JSON parse type issues

### ISSUE THREAD

**Issue by dkruchok** [angelnikolov/ts-cacheable#103]
Hi, get an error on the compilation for **DOMStorageStrategy** and **LocalStorageStrategy**

Simply fixed this with       
`return JSON.parse(data || '{}') || {};`

In this line:
<img width="650" alt="Screenshot 2021-03-28 at 18 57 09" src="https://user-images.githubusercontent.com/11375256/112758505-748ca300-8ff7-11eb-8e0c-3aeb3fa8fd46.png">

But you can add more checks of course =)

<img width="1287" alt="Screenshot 2021-03-28 at 18 54 31" src="https://user-images.githubusercontent.com/11375256/112758464-355e5200-8ff7-11eb-8df3-4e1fafcbbcbb.png">

Thanks.

```
    "@angular/cli": "^10.1.4",
    "rxjs": "^6.6.6",
    "rxjs-compat": "^6.6.6",
    "ts-cacheable": "^1.0.4",
    "ts-node": "~3.2.0",
    "tslint": "~6.1.0",
    "typescript": "3.9.6"
```

**Comment by angelnikolov** [comment]
@dkruchok Hm, is there a reason you are compiling the library? You should be using the library through the already-compiled javascript artifacts which are published.

**Comment by dkruchok** [comment]
I agree, that's can be my local issue because previously everything was Ok for a while. But I created a custom cache storage strategy and that's happened. Maybe my lining just too strict =)
But anyhow that's a piece of code that can be improved =)
`localStorage.getItem()` can return either a string or null. And `JSON.parse()` requires a string, so it would be nice to check the `localStorage.getItem()` result before pass this to the parse method.

**Comment by angelnikolov** [comment]
To be honest, I'd rather let this fail since this could be a symptom to something else going on in user code which needs attention. Closing for now, but please reopen if you still have an issue.

**Comment by jono-coder** [comment]
Hi.  I'm also finding this to be an issue.  I change the source code every time a new release comes along.  This error has been at least around since a couple of Angular versions back.

All that I'm doing is a "npm install ts-cacheable" which creates a line in package.json.  The error occurs when running the "ng server..." command.

Angular 14.2.6
