### ISSUE TITLE
How to keep cache isolated between different users ?

### ISSUE THREAD

**Issue by fasidOnGit** [angelnikolov/ts-cacheable#112]
Let us consider the following method

```
@Cacheable()
  getOrders() {
    return this.http
    .get(`${environment.api}/orders`);
  }
```
If I switch users in the same machine in the same window (like logout and login). I see that the cache from the previous user is used for the currently logged-in user. which yields me totally wrong set of values.

I also tried to set the `globalCacheKey` to be a unique id to isolate the cache between multiple users. But it doesn't work.
 
Thanks in advance.

**Comment by fasidOnGit** [comment]
`globalCacheKey` is partially fixing the issue. It does create unique entries in `localStorage`, But when I change the value of `globalCacheKey` again, it doesn't create a new entry for that in `localStorage` rather, still use the old one. is it intended ?

**Comment by angelnikolov** [comment]
Hey @fasidOnGit, I think this should be left to user land since we cant make any assumptions on when and how to clear the cache.
The global cache key is just for the purposes of name-spacing your cache storage.

**Comment by fasidOnGit** [comment]
> The global cache key is just for the purposes of name-spacing your cache storage.

That only works during the app bootstrap. switching reactively between cache key looks like not possible.

**Comment by angelnikolov** [comment]
Correct, it only works once. For further separation you'd likely create your own storage strategy which switches between multiple namespaces

**Comment by fasidOnGit** [comment]
Alright, thanks for the explanation.
