### ISSUE TITLE
inMemoryStorageStrategy: What is the in-memory size that can be utilized using the cacheable decorator?

### ISSUE THREAD

**Issue by gurramswadeep** [angelnikolov/ts-cacheable#115]
I want to use in-memory storage strategy for caching in my angular application!

Question1: Do we have any limit for in-memory cache size and what is the size?

Question2: Can we assign in-memory size to "maxCacheCount"? Since size is in multiple formats(kb/gb/bytes). If Yes, which format should be used to assign the in-memory size to maxCacheCount?

**Comment by angelnikolov** [comment]
Hey @gurramswadeep. The `maxCacheCount` just defines the `count` of caches per method. It does not define it in bytes. I guess you can calculate that yourself, based on what you expect the response to be and the maximum amount of memory you'd want to use. There's no limit on how much the cache size can be, that depends on the browser running your application.

**Comment by angelnikolov** [comment]
@gurramswadeep Please open a new issue if my answer wasn't enough for you.
