### ISSUE TITLE
Adapt description about "Cache busting" when different parameters are used

### ISSUE THREAD

**Issue by Rhobal** [angelnikolov/ts-cacheable#124]
The description contains the following information:

> If we call this method by `service.getUser(1)`, its return value will be cached and returned, up until the method is called with a different parameter. Then the old cache will be busted and a new one will take its place.

To me, this description is misleading and usefulness would be very limited. My understanding is that the result for the previous parameter remains in the cache (not "busted") and the result for the new parameter is also cached. 

Also interesting would be the information whether the same objects are returned (i.e. manipulation of the cached results also modify the objects in the cache), or if deep copies of the cached objects are returned

**Comment by Rhobal** [comment]
Thanks for the quick response and clarification.
`maxCacheCount` description reads `maximum allowed unique caches (same parameters)`, while just above, it reads "different parameters"

**Comment by angelnikolov** [comment]
@Rhobal Hm, well spotted. It doesn't make sense for it to be `(same parameters)`. Will update it, thanks!

**Comment by angelnikolov** [comment]
@Rhobal Updated, thanks for reporting this!
