### ISSUE TITLE
Question: Serve the cached response and get the latest data in background

### ISSUE THREAD

**Issue by kalpeshhpatel** [angelnikolov/ts-cacheable#135]
Is there a provision to serve the cached response first if available in the cache (local storage or session storage) and at the same time in the background, fetch the latest data from the API so that next time when we request for the data, we get the latest snapshot of the data.

If not, any pointers on how we can achieve this using custom `IStorageStrategy` implementation?

- Thank you

**Comment by angelnikolov** [comment]
@kalpeshhpatel This is possible with a custom `IAsyncStorageStrategy` if you are willing to use promise-based cacheables (i.e - @PCacheable). It would have been possible if we had async Observable cache decorators, but right now we don't.
There is another request for those [here](https://github.com/angelnikolov/ts-cacheable/issues/136) but unfortunately, I myself don't have time for it now.

**Comment by kalpeshhpatel** [comment]
Thanks @angelnikolov for the pointers. Let me try it out and update
