### ISSUE TITLE
Question: How to set Storage Strategy at Global Level

### ISSUE THREAD

**Issue by Mavrick2020** [angelnikolov/ts-cacheable#141]
Hi,
I tried setting the storage strategy at the Global level where I am initializing the app. However, I do not see the LocalStorageStrategy in place. Below is the code snippet. Please review and let me know the changes required.

providers: [
    { 
      provide: APP_INITIALIZER, 
      useFactory: init_app, 
      deps: [AppInitializerService], 
      multi: true 
    },
    InterceptorProviders,
  ],

export function init_app(appInitializer: AppInitializerService) {
  console.log("inside init_app");
  GlobalCacheConfig.storageStrategy = LocalStorageStrategy;
  return () => appInitializer.initApp();
}

**Comment by angelnikolov** [comment]
@Mavrick2020 Probably a bit late, but you gotta do this, before your Angular app kicks in.
So put it literally where your imports are
GlobalCacheConfig.storageStrategy = LocalStorageStrategy;
