### ISSUE TITLE
Release number 

### ISSUE THREAD

**Issue by aycauzel** [angelnikolov/ts-cacheable#93]
Hello,

According to npm page https://www.npmjs.com/package/ngx-cacheable, this code's latest release 1.4.3.
Could you create 1.4.3 tag/release  also in here? We used these specific release for software clearance.

Thanks.

**Comment by angelnikolov** [comment]
@aycauzel The library's name has been updated to `ts-cacheable` and it can be found [here](https://www.npmjs.com/package/ts-cacheable).
Added a new release to reflect that change.
