### ISSUE TITLE
Bust only one Cache in maxCacheCount

### ISSUE THREAD

**Issue by Stefan-Kosker** [angelnikolov/ts-cacheable#94]
Hey! Great Plug-in. I love it. 

I have a question about busting a cache when I have maxCacheCount. 

I have a function which I cache with maxCacheCount 20, since I have around these numbers different params, which repeats themselves.
```
functionName(param: string): HTTPResponse {
//do a HTTP Call
}
```

Now, I can make changes to only one of these values and this value must be requested again from Backend, without touching the other 19 caches, if possible. CacheBuster removes all the caches. Is there a way to achieve this?

Have a great day

**Comment by angelnikolov** [comment]
@Stefan-Kosker 
Good question. Right now there isn't a way to selectively remove a specific cache member from the Storage. To do that, I suggest you create a new `StorageStrategy` by implementing the `IStorageStrategy` interface. You can see our fairly simple memory storage implementation [here](https://github.com/angelnikolov/ts-cacheable/blob/master/common/InMemoryStorageStrategy.ts).
Then, in the new storage strategy you can choose a different storing mechanism. For example, you can store your cache in memory, but also expose access to it so you can later clear the specific cached data when you know that it has updated on the server.
Let me know if that helps @Stefan-Kosker

**Comment by Stefan-Kosker** [comment]
Hello @angelnikolov thank you for your quick response! 

Due to strict deadlines, we decided to implement the easy solution: Bust all caches. Requesting other 19 will probably cause a bit higher traffic. After busting all the cache, the probability of new requests are low enough according to our requirements engineering team though. 

Thank you for your support and huge appreciation for awesome plug-in. Have a great one

**Comment by dmbaker90** [comment]
I made this montrosity to solve this problem, in case it helps others.  

    @Cacheable({
        cacheBusterObserver: worklistRemainingNotifier$,
        maxCacheCount: 100,
        storageStrategy: DOMStorageStrategy,
    })
    public getWorklistRemaining(workqueueId: string, worklistIdOrName: string, dto: SearchBarDto): Observable<number> {
        const url = `${this.apiUrl}/workqueue/getWorklistRemaining/${workqueueId}/${worklistIdOrName}`;
        return this.http.get<number>(url, { params: <any>dto });
    }

    // The above getWorklistRemaining method uses LocalCahce to save the calculation.
    // This method finds the worklist in the cache and clears it, so the next time we call the above method, it re-calculates
    public clearWorklistCacheByWorklistId(worklistIdOrName: string) {
        // Get the cache belonging to ngx-cacheable
        const worklistCache = localStorage.getItem(GlobalCacheConfig.globalCacheKey);
        const parsed = JSON.parse(worklistCache);
        // Get the section belonging to method WorklistRemaining
        const getWorklistRemainingCache = parsed['DataService#getWorklistRemaining'];
        // Get the cache for the matching worklist id
        const matchIndex = getWorklistRemainingCache.findIndex(w => w.parameters[1] === worklistIdOrName);
        if (!matchIndex) { return; }
        parsed['DataService#getWorklistRemaining'].splice(matchIndex, 1);
        localStorage.setItem(GlobalCacheConfig.globalCacheKey, JSON.stringify(parsed));
    }
