### ISSUE TITLE
Access cached date

### ISSUE THREAD

**Issue by matthew2564** [angelnikolov/ts-cacheable#95]
Hi there,

I'm wondering if it is possible to access the time the cache was created? Ideally I need to compare the cached date to another date i have in order to work out whether or not to bust the cache.

Any help/advice would be great.

Thanks!

**Comment by angelnikolov** [comment]
@matthew2564 Good question. To do that, I suggest you create a new `StorageStrategy` by implementing the `IStorageStrategy` interface. You can see our fairly simple memory storage implementation [here](https://github.com/angelnikolov/ts-cacheable/blob/master/common/InMemoryStorageStrategy.ts).
If you check this out https://github.com/angelnikolov/ts-cacheable/blob/master/cacheable.decorator.ts#L113, you will see that every cache is added with the `created` property which is the date.
In your strategy you can expose a global method to expose the cached data or maybe expose a custom cache busting method which will manually remove just the data you want to remove.

**Comment by matthew2564** [comment]
Thanks for the prompt reply @angelnikolov. So do you mean something like this?

`  @Cacheable({
    maxAge: (60 * minute),
    maxCacheCount: 80,
    storageStrategy: InMemoryStorageStrategy
  })
  read(id: string | number): Observable<T> {
    // this is value i need to compare against cached date, not sure how i get this value into the storage strategy though?
   console.log(this.timeAsLong);`

   // http call
}

Inside the InMemoryStorageStrategy I was thinking about something like

`  bustExpiredCaches = (cachePairs: ICachePair<any>[], updatedAt: number) => {
    cachePairs.forEach((cachePair: ICachePair<any>) => {
      if ((updatedAt > cachePair.created.getTime())) {
        const [endpoint] = cachePair.parameters;
        this.removeByEndpoint(endpoint);
      }
    });
  }
  removeByEndpoint = (endpoint: string) => {
    const res = this.cachePairs.findIndex((cachePair: ICachePair<any>) => cachePair.parameters.includes(endpoint));
    if (res < 0) return;
    this.cachePairs.splice(res, 1);
  }`

Might have not fully implemented what you suggested or in a correct way, does above make sense or would you advise something different?

Once again, thanks!

**Comment by angelnikolov** [comment]
@matthew2564 I was thinking about something in the lines of what you already have but add that to a custom `CustomStorageStrategy`. There you can expose a static property where you can store all of you cached data (for all decorators which use this strategy.
```ts
export class CustomStorageStrategy implements IStorageStrategy {
    public static storage: any[]; 
    ...all methods from IStorageStrategy are here and they only read/write to the public storage property
}
```
Then in your callsite - 
```ts
@Cacheable({
maxAge: (60 * minute),
maxCacheCount: 80,
storageStrategy: CustomStorageStrategy
})
read(id: string | number): Observable {
/// 1. get the storage from CustomStorageStrategy.storage
/// 2. make your comparison
/// 3. remove the data you want
/// 4. you can even add this as another static method in the strategy itself if you want that to be reusable from other metods too
/// 5. http call
}
```
