### ISSUE TITLE
Does Ts-Cachable support typed observables?

### ISSUE THREAD

**Issue by jeffrey-hines** [angelnikolov/ts-cacheable#96]
With the following code
    
    @Cacheable()
    getCurrentDate(asyncLoading?: boolean): Observable<Date> {
      const headers = asyncLoading ? new HttpHeaders().set('noLoader', 'noLoader') : undefined;
      return this.http.get<string>(`${this.BASE_URL}/CurrentDate`, { headers })
        .pipe(map(response => new Date(response)));
    }

I get the following error...

 ERROR in src/app/shared/services/capacity-api.service.ts(145,4): error TS2345: Argument of type 'TypedPropertyDescriptor<(asyncLoading?: boolean | undefined) => Observable<Date>>' is not assignable to parameter of type 'TypedPropertyDescriptor<ICacheable<Observable<any>>>'.
      Type '(asyncLoading?: boolean | undefined) => Observable<Date>' is not assignable to type 'ICacheable<Observable<any>>'.
        Type 'Observable<Date>' is not assignable to type 'Observable<any>'.
          Types of property 'source' are incompatible.
            Type 'import("C:/Users/jhines/source/repos/capacityweb/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import("C:/Users/jhines/source/repos/capacityweb/node_modules/ts-cacheable/node_modules/rxjs/internal/Observable").Observable<any>'.
              Types of property 'operator' are incompatible.
                Type 'import("C:/Users/jhines/source/repos/capacityweb/node_modules/rxjs/internal/Operator").Operator<any, any>' is not assignable to type 'import("C:/Users/jhines/source/repos/capacityweb/node_modules/ts-cacheable/node_modules/rxjs/internal/Operator").Operator<any, any>'.
                  Types of property 'call' are incompatible.
                    Type '(subscriber: import("C:/Users/jhines/source/repos/capacityweb/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("C:/Users/jhines/source/repos/capacityweb/node_modules/rxjs/internal/types").TeardownLogic' is not assignable to type '(subscriber: import("C:/User
s/jhines/source/repos/capacityweb/node_modules/ts-cacheable/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("C:/Users/jhines/source/repos/capacityweb/node_modules/ts-cacheable/node_modules/rxjs/internal/types").TeardownLogic'.
                      Types of parameters 'subscriber' and 'subscriber' are incompatible.
                        Type 'Subscriber<any>' is missing the following properties from type 'Subscriber<any>': _parent, _parents, _addParent

Can I use Typed Observables?

**Comment by angelnikolov** [comment]
@jeffrey-hines There was an erroneous rxjs dependency in the project, can you try with `Version
1.0.2` which I just published?

**Comment by jeffrey-hines** [comment]
That worked. Thx.

Where is the best place to setup the global settings? 

I can get the caching to work in I define the settings locally, but caching doesn't work if I define globally.

**Comment by angelnikolov** [comment]
I'd add it at a place as early as possible in your application lifecycle. Doesnt matter where exactly, just before any logic which requires it .

**Comment by jeffrey-hines** [comment]
Thanks
